[package]
name = "memcached-ebpf-proxy-cache-common"
version = "0.1.0"
edition = "2021"

[features]
default = []
user = ["aya"]

[dependencies]
aya = { version = "0.12", optional = true }
aya-ebpf = "0.1.0"

[lib]
path = "src/lib.rs"
